### ISSUE TITLE
Adicionar menu mobile e ajustar UX

### ISSUE THREAD

**Issue by PauloRev** [rafa-acioly/fastcep#10]
Acho interessante o projeto ter um menu quando estiver no mobile e o mesmo ser fixo e também estar adicionando um cursor tipo pointer onde for clicável, assim poderia estar melhorando a experiência do usuário.

**Comment by rafa-acioly** [comment]
concordo com você @PauloRev, fique a vontade para enviar o PR quando quiser.

**Comment by PauloRev** [comment]
Desculpas, sou novo aqui e eu acabei confundindo o projeto com o QuickCep que é onde tem sua API, ai acabei caindo aqui pois estava pelo cell e não percebi kkk...Mas vou analisar esse para ver em que posso ajudar, novamente peço desculpas pelo engano :)

**Comment by rafa-acioly** [comment]
sem problema.
